name=input("what is your name?: ")
age=int(input("how old are you?: "))
height=float(input("How tall are you?: "))
print("your name is: "+name)
print("your name is: "+str(age))
print("your name is: "+str(height)+"cm")